[build]
  command = "hugo"
  publish = "public"

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[build.environment]
  HUGO_VERSION = "0.147.9"